version: "3.8"
services:
  mysql:
    image: mysql:8.0.25
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    command:
      --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
